### ISSUE TITLE
Add support for oneOf

### ISSUE THREAD

**Issue by patrickkwang** [ranking-agent/json-schema-fuzz#16]
https://json-schema.org/understanding-json-schema/reference/combining.html#oneof

**Comment by patrickkwang** [comment]
I believe that we can implement this as a combination of `anyOf`, `allOf`, and `not`.

```yaml
oneOf:
  - type: integer
    multipleOf: 5
  - type: integer
    multipleOf: 3
 ```

should be equivalent to

```yaml
anyOf:
  - allOf:
    - type: integer
      multipleOf: 5
    - not:
        type: integer
        multipleOf: 3
  - allOf:
    - type: integer
      multipleOf: 3
    - not:
        type: integer
        multipleOf: 5
 ```
